root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
plugins:
  - react
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: detect
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    typescript:
      alwaysTryTypes: true

rules:
  no-trailing-spaces: error
  curly: error
  brace-style: error
  no-multi-spaces: error
  space-infix-ops: error
  space-unary-ops: error
  no-whitespace-before-property: error
  func-call-spacing: error
  space-before-blocks: error
  keyword-spacing:
    - error
    - before: true
      after: true
  comma-spacing:
    - error
    - before: false
      after: true
  comma-style:
    - error
    - last
  comma-dangle:
    - error
    - always-multiline
  space-in-parens:
    - error
    - never
  block-spacing: error
  array-bracket-spacing:
    - error
    - never
  object-curly-spacing:
    - error
    - always
  key-spacing:
    - error
    - mode: strict
  arrow-spacing:
    - error
    - before: true
      after: true
  arrow-body-style: off

